/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerRemoveDefaultAddressRequest
 */
public class CustomerRemoveDefaultAddressRequestTest {
    private final CustomerRemoveDefaultAddressRequest model = new CustomerRemoveDefaultAddressRequest();

    /**
     * Model tests for CustomerRemoveDefaultAddressRequest
     */
    @Test
    public void testCustomerRemoveDefaultAddressRequest() {
        // TODO: test CustomerRemoveDefaultAddressRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'addressId'
     */
    @Test
    public void addressIdTest() {
        // TODO: test addressId
    }

}
