/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerNewsletterRequest
 */
public class CustomerNewsletterRequestTest {
    private final CustomerNewsletterRequest model = new CustomerNewsletterRequest();

    /**
     * Model tests for CustomerNewsletterRequest
     */
    @Test
    public void testCustomerNewsletterRequest() {
        // TODO: test CustomerNewsletterRequest
    }

    /**
     * Test the property 'newsletterGrn'
     */
    @Test
    public void newsletterGrnTest() {
        // TODO: test newsletterGrn
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'subscribed'
     */
    @Test
    public void subscribedTest() {
        // TODO: test subscribed
    }

}
