/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CustomerCreateConsentRequest;
import org.openapitools.client.model.CustomerEMFields;
import org.openapitools.client.model.CustomerNewsletterRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerSubscriberResponseWithNewsletterRequest
 */
public class CustomerSubscriberResponseWithNewsletterRequestTest {
    private final CustomerSubscriberResponseWithNewsletterRequest model = new CustomerSubscriberResponseWithNewsletterRequest();

    /**
     * Model tests for CustomerSubscriberResponseWithNewsletterRequest
     */
    @Test
    public void testCustomerSubscriberResponseWithNewsletterRequest() {
        // TODO: test CustomerSubscriberResponseWithNewsletterRequest
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'birthdate'
     */
    @Test
    public void birthdateTest() {
        // TODO: test birthdate
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'em'
     */
    @Test
    public void emTest() {
        // TODO: test em
    }

    /**
     * Test the property 'preferredLocale'
     */
    @Test
    public void preferredLocaleTest() {
        // TODO: test preferredLocale
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'newsletters'
     */
    @Test
    public void newslettersTest() {
        // TODO: test newsletters
    }

    /**
     * Test the property 'consent'
     */
    @Test
    public void consentTest() {
        // TODO: test consent
    }

}
