/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CustomerSubscriberResponseWithNewsletterRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerUpdateSubscriberRequest
 */
public class CustomerUpdateSubscriberRequestTest {
    private final CustomerUpdateSubscriberRequest model = new CustomerUpdateSubscriberRequest();

    /**
     * Model tests for CustomerUpdateSubscriberRequest
     */
    @Test
    public void testCustomerUpdateSubscriberRequest() {
        // TODO: test CustomerUpdateSubscriberRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'subscriber'
     */
    @Test
    public void subscriberTest() {
        // TODO: test subscriber
    }

    /**
     * Test the property 'fieldMask'
     */
    @Test
    public void fieldMaskTest() {
        // TODO: test fieldMask
    }

}
