/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ListCustomersRequestFilterDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerListCustomersRequestFilter
 */
public class CustomerListCustomersRequestFilterTest {
    private final CustomerListCustomersRequestFilter model = new CustomerListCustomersRequestFilter();

    /**
     * Model tests for CustomerListCustomersRequestFilter
     */
    @Test
    public void testCustomerListCustomersRequestFilter() {
        // TODO: test CustomerListCustomersRequestFilter
    }

    /**
     * Test the property 'genders'
     */
    @Test
    public void gendersTest() {
        // TODO: test genders
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'countries'
     */
    @Test
    public void countriesTest() {
        // TODO: test countries
    }

    /**
     * Test the property 'agentGrn'
     */
    @Test
    public void agentGrnTest() {
        // TODO: test agentGrn
    }

}
