/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerCreateConsentRequest
 */
public class CustomerCreateConsentRequestTest {
    private final CustomerCreateConsentRequest model = new CustomerCreateConsentRequest();

    /**
     * Model tests for CustomerCreateConsentRequest
     */
    @Test
    public void testCustomerCreateConsentRequest() {
        // TODO: test CustomerCreateConsentRequest
    }

    /**
     * Test the property 'preferences'
     */
    @Test
    public void preferencesTest() {
        // TODO: test preferences
    }

}
