/*
 * CDP Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CustomerConsent;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerListConsentsResponse
 */
public class CustomerListConsentsResponseTest {
    private final CustomerListConsentsResponse model = new CustomerListConsentsResponse();

    /**
     * Model tests for CustomerListConsentsResponse
     */
    @Test
    public void testCustomerListConsentsResponse() {
        // TODO: test CustomerListConsentsResponse
    }

    /**
     * Test the property 'consents'
     */
    @Test
    public void consentsTest() {
        // TODO: test consents
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
